server:
  port: 9092
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql:///shop1810

  #配置rabbitMQ
  rabbitmq:
    host: 192.168.72.128
    port: 5672
    username: admin
    password: admin
    virtual-host: /admin

#配置dubbo
dubbo:
  application:
    name: sso_service
  registry:
    address: zookeeper://192.168.72.128:2181
  protocol:
    name: dubbo
    port: 20883
